# Generated by Django 5.2.9 on 2026-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('kicker', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('bg_image', models.ImageField(upload_to='slides/')),
                ('primary_text', models.CharField(default='Explore Services', max_length=60)),
                ('primary_url_name', models.CharField(default='services', max_length=60)),
                ('secondary_text', models.CharField(default='Free Counseling', max_length=60)),
                ('secondary_type', models.CharField(choices=[('url', 'URL'), ('modal', 'Modal')], default='modal', max_length=10)),
                ('secondary_url_name', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
