# Generated by Django 5.2.9 on 2026-01-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Everything You Need — In One Place', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='Quick overview of our pages. Click any section to explore more.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✨', max_length=10)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=220)),
                ('action_type', models.CharField(choices=[('url', 'URL'), ('modal', 'Modal')], default='url', max_length=10)),
                ('url_name', models.CharField(blank=True, max_length=60)),
                ('modal_id', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.homesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
