# Generated by Django 5.2.9 on 2026-01-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Fine Diamond Education Foundation Pvt. Ltd.', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Pvt. Ltd. • Kathmandu, Nepal', max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('phone', models.CharField(blank=True, default='+977-1-5911111', max_length=40)),
                ('email', models.EmailField(blank=True, default='info@finediamond.edu.np', max_length=254)),
                ('address', models.CharField(blank=True, default='Dharma Chakra Galli, Badhbazar, Kathmandu, Nepal', max_length=200)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('google_map_embed', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
